### ISSUE TITLE
Module 05 Demo 01: Omnichannel signup instructions missing, but potentially useful

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#10]
# Module: 05
#### Step: 00

Description of issue

This may be an issue more for orgs that use pre-provisioned/pre-provided Dynamics Tenants, wherein the Omnichannel functionality referenced for this Demo/Lab is not pre-provisioned by default, however I am wondering if it might be a good idea to nevertheless include a short 'Note' - or even just the reference to the URL - in the Demo 05 instructions.

Perhaps including a basic step-by-step process to setup a trial Omnichannel account to utilize along with the existing Dynamic Tenant.

For example, this takes a short amount of time to enroll/configure - but does appear to allow the access Omnichannel when used in conjunction with a Tenant not already pre-provisioned as such:  'Get a Dynamics 365 trial instance' section of Try channels in Omnichannel for Customer Service | Microsoft Docs) 

 -- https://docs.microsoft.com/en-us/dynamics365/customer-service/try-channels

Repro steps:

1.
1.
1.

**Comment by berkenbrack** [comment]
Hello Team:

Has there been any  movement on this issue please? Thank you.

**Comment by TesterTesterson1004** [comment]
To add some additional clarifications:  It appears that in the tenant usage scenario, because Omnichannel is neither preprovisioned w/OC, nor 'cleaned' when the Tenants are deprovisioned for the next class setting, that the OC trial can only be used once per Tenant.

Preferably, the lack of OC config would be taken care of within the Tenant - i.e., provisioned automatically, and de-provisioned appropriately for future Tenant reuse.  Failing that, it would likely be needed to clarify in any instructions on how to use the OC free trial that an Instructor needs to use their own personal account to which to redeem the OC trial.
