### ISSUE TITLE
M01 Exercise01 Task 1 step 1, change the link

### ISSUE THREAD

**Issue by Rehan-Majeed** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#13]
# Module: 01
#### Step: 01

Description of issue: Given link is for a specific tenant and not everyone can access it. 

Repro steps:

1. Go to the environment you created earlier in the previous module.
2.	Click the link under Environment URL.

**Comment by julians1966** [comment]
The labs have been majorly refreshed in the October release and all steps validated. The link has been removed.
