### ISSUE TITLE
There is no drop down for service to select "Maintenance."

### ISSUE THREAD

**Issue by hope77777** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#16]
# Module: 01
#### Step: 04

Description of issue:

Not a show stopper, but
There is no drop down for service to select "Maintenance."

Repro steps:
https://github.com/MicrosoftLearning/MB-230-Dynamics365forCustomerService/blob/master/Instructions/Labs/LAB%5BMB-230%5D_M01Lab01_Creating_Cases.md#task-3--create-case
![2021-10-19_102459](https://user-images.githubusercontent.com/62302805/137931351-9d694a2d-689f-4e1a-89aa-7413d1633fa2.JPG)

**Comment by TesterTesterson1004** [comment]
@julians1966 if this perhaps a browser rendering issue, can you let us know which browser and version you are using successfully?

**Comment by TesterTesterson1004** [comment]
Hmm, very strange.  Can you confirm behavior on a new/latest Edge version?   (I don't recognize Edge v 41.16299.15.0, that seems...very old)

In any case, I've tried both within a standard Win10 VM w/recent Edge - v83.0.478.61, on my desktop with same Edge version & also Chrome v94.0.4606.81, and see the problem in all of them identically.

This *feels* like a browser/rendering issue, but I simply cannot explian why, if that was so, such disparate results between testing of versions.

**Comment by julians1966** [comment]
That is the version of Edge in the VM supplied by Valorem. 
I have updated to Edge to 95.0.0120.30 and it works ok on that too

**Comment by julians1966** [comment]
I have recorded my steps on two different ALH 

https://user-images.githubusercontent.com/29278645/138347038-e7e9de13-d32c-4c86-9264-be96a0e5bc1b.mp4

https://user-images.githubusercontent.com/29278645/138347332-b7d4ecc6-6584-40ef-8453-96b314cfdd60.mp4
