### ISSUE TITLE
Instructions Don't Match Content

### ISSUE THREAD

**Issue by zeeb33** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#45]
# Lab: 01
#### Step: 05, 07

Description of issue
Step 05 asks the user to find and select the account they created in Task 1 however, the function of the Customer Field searches through the Contacts list and pulls in the contacts created in Task 2.

Step 07 asks the user to enter Armband in the Product field and select Armband 100, this does not exist. 
![image](https://user-images.githubusercontent.com/42649591/161983125-4025a9af-87a6-4108-9742-d0cc7a596af3.png)
![image](https://user-images.githubusercontent.com/42649591/161983154-519d31f9-4d2a-4da4-8ea8-62039cbd82a6.png)

**Comment by trfor** [comment]
Tested and found that sample data was not being loaded in the tenant.  Once sample data was added, issue resolved.
