### ISSUE TITLE
"Agent Collaboration" lab - new?

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#54]
The updated October 2022 'MB-230T01A-ENU-ChangeLog.pdf' file indicates there has been an 'Agent Collaboration' lab added:

![image](https://user-images.githubusercontent.com/49700217/196060696-da93ba3e-9ebe-412e-835e-5e9e804ac5b6.png)

Can you clarify which document in the /Instructions corresponds to this new 'Agent Collaboration' lab?

**Comment by anjenni** [comment]
Hi there! Thank you, we had missed uploading this lab. It is now uploaded.

**Comment by TesterTesterson1004** [comment]
Thanks!  :)
