### ISSUE TITLE
MB-230 module 0, another lab problem

### ISSUE THREAD

**Issue by TrevorBarry** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#6]
# Module: 00
#### Step: 03

'Customer Service Hub' does not exist on the page that task 2 takes you to. It looks like the app was never provisioned into the lab environment.

Repro steps:

1. follow the steps

**Comment by mreherefortea** [comment]
Confirmed.  The following will allow a Sandbox environment to be created if you would like to add to the instructions:


"From the Power Platform Admin center, click + New.

In the new environment, configure the following parameters as follows:

Name: choose a unique name.

Type: sandbox

Create a database for this environment: Yes.

Click Next.

Enable Dynamics 365 apps: Yes.

Automatically deploy these apps: Customer Service (select).

Click Save."

**Comment by julians1966** [comment]
The labs now provision a complete Customer Service production instance. There is no requirement to create an environment.
