### ISSUE TITLE
Instruction Dont match content Blocker

### ISSUE THREAD

**Issue by Universo-Ap00** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#69]
Mod: 1
Lab: 1
Exercise: 2
Task: 3
Step: 4 and 7

Description of issue:
- This is a follow-up issue based off of similar issues present as shown in closed issue #45 
- Tester states that 'sample data' never populated but dont see any manual steps that reference 'Sample data'. This could possibly happen on the backend when the tenant is logged in with a trial attached. 
- Can you expand a bit on where this sample data lives and what the process is to: "Once sample data was added, issue resolved"?

**Comment by anjenni** [comment]
Hi there! Thanks for bringing this to our attention. The demo data must have changed so the instructions are updated to instruct students to pick a different product. Let me know if anything else arises.
