### ISSUE TITLE
Configure SLA’s and KPI’s in Microsoft Dynamics 365 Customer Service

### ISSUE THREAD

**Issue by indiratechno** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#71]
# Module: M02Lab01_Entitlements_and_Templates
#### Step: 6.Select the SLA tab. You should see the Case Response By SLA KPI in progress with failure time set to 1 hour's time.

Description of issue
Hello,
Can anyone please help me to sort out the issue.
I Created Entitlements , Entitlement templates and Service level agreement from D365 Customer service admin center and activated it, While testing the SLA from Customer service hub I couldn't see SLA KPI Instances under SLA tab.

Repro steps:

1.
1.
1.

**Comment by chaast** [comment]
Hi, i had the same problem. it's due to missing instructions.

To fix the issue, to go to the Details tab of the case and set the case type to Problem. 

I have asked microsoft to update the lab to include this.

**Comment by anjenni** [comment]
Hi, this issue has been retested and resolved. Thank you for bringing this to our attention!
