### ISSUE TITLE
Not able to create bookable resource records that can be used as experts

### ISSUE THREAD

**Issue by indiratechno** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#72]
# Module: M06Lab03_Agent_Collab
#### Step: 4. Configure the new Bookable resource as follows:

Resource Type: User

Contact: Alan Steiner.

Description of issue
Hello,
Can anyone please help me on this.
1.I created the user from Customer service hub  -> contacts. when I tried to add bookable resource the user is not shown in the dropdown options.
2.Then I tried creating from Microsoft 365 admin center as well but the user is not shown.

Repro steps:

1.
1.
1.

**Comment by chaast** [comment]
Hi Akn, i just used the license provided when creating the trial as part of these labs.  I recommend to address any further questions to Microsoft (I don't work for them, i am just a user like yourself).

**Comment by anjenni** [comment]
Hi akn9050 - this user is loaded into the tenant that you receive from an Authorized Lab Hoster when a user in this ILT class. Are you using a tenant through an authorized lab hoster, or are you using your own environment?

**Comment by anjenni** [comment]
Hi there! Since I cannot recreate the issue, I am going to go ahead and close this, but please open another case if you're continuing to have trouble. Thank you!
