### ISSUE TITLE
Practice Lab 4 - Routing cases - incorrect instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#74]
# Lab: 04
#### Step: 16

Description of issue

* my case was not routed to Silver queue but instead to the Bronze queue.

Repro steps:

1. Please fix step 16 to read "bronze" queue to avoid confusion with learners
2. Or please fix exercise 2, step 22  to select maintenance instead of service on the right hand side of the condition.

**Comment by anjenni** [comment]
Thank you, this has been retested and the lab instructions have been updated. Thanks so much for bringing this to our attention!
