### ISSUE TITLE
Practice lab 5 - Entitlements and SLAs - missing instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#75]
# Lab: 05
#### Step: 06

Description of issue
* When you select the SLA tab, you should see the case response by sla kpi in the grid. but this is not the case

Repro steps:

1. To fix the issue, please include an instruction on  step 5 to go to the Details tab and set the case type to Problem.

**Comment by anjenni** [comment]
Thank you, these steps have been retested and updated. Thanks for logging this.
