### ISSUE TITLE
Practise Lab 11 - App profiles - requires mention in lab instructions to navigate to admin centre

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#76]
# Lab: 11
#### Step: 04

Description of issue
App profile manager has been removed. This exercise is now redundant.

Repro steps:
![image](https://user-images.githubusercontent.com/89986870/233846058-610de23f-ec5e-4216-9855-edc37440c465.png)

![image](https://user-images.githubusercontent.com/89986870/233845968-59a88540-7022-4623-a310-fa7e6e11de33.png)

# Lab: 11
#### Step: 07

Description of issue
The template cannot be saved. An error message appears when I press save. I did not test the rest of the lab instructions as I expect this lab will be updated with descriptions of how to navigate around the Customer Service Admin Centre!

Repro steps:

![image](https://user-images.githubusercontent.com/89986870/233846837-145f3e30-d9af-4540-b8f1-c133815b7f36.png)

![image](https://user-images.githubusercontent.com/89986870/233847327-de2f5c85-1d9f-4dde-b9a3-f6bf4482acc8.png)

**Comment by chaast** [comment]
Hi, i think i found the fixes:

* Instead of navigating to app profile manager, please update the instructions to say: navigate to Customer Service Admin Centre > in the agent experience section click on workspaces > update the experience profile or session.
* The unique name prefix cannot be more than 8 characters long.

the lab can be done when you follow those steps.

**Comment by anjenni** [comment]
Hi there! Thank you for logging this bug. The lab instructions have been updated accordingly. Thank you!
