### ISSUE TITLE
Practice Lab 11 - Agent collaboration - insufficient security role, preventing execution of steps

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#77]
# Lab: Agent Collaboration
#### Step: 05 & 8

Description of issue:

It is not possible to carry out this step as you need to be a Global Administrator: 
* Turn on Microsoft Teams chats inside Dynamics 365
* On the Customer support swarming screen, ensure that Swarming is set to On.

Note: the fact that step 8 cannot be carried out, stops the user from carrying out Exercise 2.

Repro steps:

![image](https://user-images.githubusercontent.com/89986870/233847961-bfe5c5ff-08c5-441d-b85f-fa5d529e4559.png)

![image](https://user-images.githubusercontent.com/89986870/233848743-4469d078-1598-49bc-acee-03643303c378.png)

**Comment by ArturoBravo111** [comment]
Experiencing the same issue using LOD instances, any word from Microsoft? More than one month have passed since initially informed.
