### ISSUE TITLE
Practice Lab 12 - Customer Service Insights - incorrect instructions

### ISSUE THREAD

**Issue by chaast** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#78]
# Lab: 12
#### Step: 06

Description of issue

* cannot enable historical analysis... see images below.... please correct instructions for this lab...

Repro steps:

![image](https://user-images.githubusercontent.com/89986870/233849054-7478a4d8-8a3a-43d1-904d-fc605395e3d1.png)

![image](https://user-images.githubusercontent.com/89986870/233848959-683c12e3-beb4-4b6d-879b-c71d562a86c6.png)

**Comment by anjenni** [comment]
Hi there! Thanks so much for bringing this to our attention. This issue is addressed in the 6/9 update that we pushed today. Please let me know if any other issues arise.
