### ISSUE TITLE
UI update has changed the location of the App profile manager in Lab 11 instructions

### ISSUE THREAD

**Issue by brookbeckertesting** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#80]
# Lab: 11
#### Step: 04

Description of issue
Instructions describe App profile manager being located under the ellipsis drop-down menu under Customer Service workplace, but it's now under Apps.

Repro steps:

Navigate to the Power Apps Maker portal https://make.powerapps.com/.

Select the {TENANTPREFIX} Dynamics 365 environment.

Click on Apps

Click on the ellipsis (…) in the Customer Service workspace app and select App profile manager.

Click App profiles. You will see profiles for Customer Service workspace and Omnichannel for Customer Service.

Select the Customer Service workspace - default profile.

Review the General, Session templates, Productivity Pane, and Channels tabs.

![image](https://github.com/MicrosoftLearning/MB-230-Dynamics365forCustomerService/assets/94069201/c8f5d30b-d404-43a7-ad84-b7e6106d4bfe)

**Comment by anjenni** [comment]
Thank you for logging this error. This has been resolved. Thank you!
