### ISSUE TITLE
Practice Lab 11 – App profiles Broken steps

### ISSUE THREAD

**Issue by ArturoBravo111** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#81]
# Module: 06
#### Step: 06

Description of issue

I found too many issues on this lab, to begin App profile manager is now deprecated as indicated here: https://learn.microsoft.com/en-us/dynamics365/app-profile-manager/app-profile-manager

Hence many steps need a rewrite, when is the timeframe to get this lab updated to reflect UI changes?

**Comment by anjenni** [comment]
Hi ArturoBravo111, thanks so much for logging this. We are pushing an update this Friday (6/9) to fix this lab and a few other issues. I will close this Issue on that day.

**Comment by anjenni** [comment]
Hi there! This issue was resolved today with an update to the lab instructions. Thanks again for logging the issue.
