### ISSUE TITLE
MB-230T01-A Dynamics 365 for Customer Engagement for Customer Service Issue

### ISSUE THREAD

**Issue by InstrovateSakshi250399** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#83]
# Module: 4 
![Screenshot 2023-06-16 211419](https://github.com/MicrosoftLearning/MB-230-Dynamics365forCustomerService/assets/137225731/9df7178c-b38a-443e-b989-d074a1a8a5a4)
![Screenshot 2 ](https://github.com/MicrosoftLearning/MB-230-Dynamics365forCustomerService/assets/137225731/d42998de-8040-4dbc-b3b7-b0b630bc218f)
![Screenshot 3](https://github.com/MicrosoftLearning/MB-230-Dynamics365forCustomerService/assets/137225731/3140bb6f-8a5a-491b-b9ed-23b93e88f1b8)

##Lab/Demo: 07 Customer Voice
###Exercise: 03 Send survey when a case is resolved
####Task: 1 Configure automation
##### Step: 16 Clear the Email template field and select the Case Resolution template You created.

Description of issue
I am not able to select the correct email template as it is asking me about the customer voice project which is again I am not able to select from the dropdown menu.

**Comment by InstrovateSakshi250399** [comment]
I have tried creating the flow as per the instructions from the template available in customer voice send tab only but it still asks me to select customer voice project and survey which is missing. The moment I am trying to click create it show the error that is the reason I am not able to access this flow from Power Automate.

**Comment by anjenni** [comment]
Hi there! Thanks a lot for bringing this to our attention. I'll be looking into this this week and hope to have it resolved by end of week.

**Comment by anjenni** [comment]
Hi there! I've retested the issue and corrected the lab with updated instructions. Please let me know if any other issues arise. Thanks again for raising the issue.
