### ISSUE TITLE
Previous lab data not cleared down

### ISSUE THREAD

**Issue by julians1966** [MicrosoftLearning/MB-230-Dynamics365forCustomerService#85]
The lab environment contained large amounts of data from previous Dynamics 365 courses 

It took me several hours to clear down the data which must be deleted in a defined order due to dependencies and cascade behaviours in between the Dynamics 365 tables

Environment: WWLCLOUDCE000133

This is the order to clear the tables:

- Booking Timestamp
- Booking Journal
- Geofence
- Geofence events
- Schedule Boards (except for Initial dashboard)
- Bookable Resource Bookings
- Booking Notification Codes
- Resource Requirements
- Requirement Groups
- Requirement Group Templates
- Requirement Resource Preferences
- Requirements Priorities
- Bookable Resource Groups
- Proficiency models
- Work Hours Templates
- Work Orders
- Time Entries
- Agreements
- Customer Assets
- Customer Asset Categories
- Functional Locations
- Invoices
- Orders
- Quotes
- Opportunities
- Purchase Order Products
- Purchase Orders
- RTVs
- RMA Receipts
- RMAs
- Inventory Adjustment Products
- Inventory Adjustments
- Inventory Transfers
- Product Inventory
- Inventory Journals
- Warehouses (except for Main)
- Territories
- Tax Codes
- Payments Terms
- Incident Types
- Work Order Types
- Work Order Substatuses
- Resolutions
- Service Task Types
- Inspection Templates (Deactivate if published)
- Field Service Price List Item
- Price List Item
- Product
- Price List
- Discount List
- Unit Groups (except Default Unit and Distance Units of Measure for Resource and Asset Location Management)
- Service Activities
- Services
- Time Group Detail
- Fulfilment Preferences
- Facilities/Equipment
- Bookable Resources
- Bookable Resource Categories
- Requirement Characteristics
- Characteristics
- Organizational Units
- Business Closures
- Routing Rules Sets (Deactivate first)
- Record creation and update rules (Deactivate first)
- Entitlements (Deactivate first)
- Entitlement Templates
- Service Level Agreements (Deactivate first)
- SLA KPIs (Deactivate first)
- Holiday Schedules
- Customer Service Calendars
- Application tabs (not created by SYSTEM)
- Session Templates (not created by SYSTEM)
- Agent Scripts
- Agent experience profiles (except for 3 locked profile)
- Cases
- Contacts
- Accounts
- Basic Queues (not created by System and owner does not begin with # and name does not begin with <)

**Comment by bpmoring** [comment]
Thanks for bringing this up Julian. I have brought this up to the team to identify how to make this a better experience.
